import avatar from "./avatar.jpg";
import avatar2 from "./avatar2.jpg";
import avatar3 from "./avatar3.png";
import avatar4 from "./avatar4.jpg";

const employeesData = [
  {
    EmployeeID: 1,
    Name: "Shubham Joshi",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 2,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 3,
    Name: "Shubham Joshi",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 4,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 5,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 6,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 7,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 8,
    Name: "Shubham Joshi",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 9,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 10,
    Name: "Shubham Joshi",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 11,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 12,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 13,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 14,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 15,
    Name: "Shubham Joshi",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 16,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 17,
    Name: "Shubham Joshi",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 18,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 19,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 20,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 21,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 22,
    Name: "Shubham Joshi",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 23,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 24,
    Name: "Shubham Joshi",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 25,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 26,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 27,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 28,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 29,
    Name: "Shubham Joshi",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 30,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 31,
    Name: "Shubham Joshi",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 32,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 33,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 34,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 35,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 36,
    Name: "Shubham Joshi",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 37,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 38,
    Name: "Shubham Joshi",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 39,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 40,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 41,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 42,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 43,
    Name: "Shubham Joshi",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 44,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 45,
    Name: "Shubham Joshi",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 46,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 47,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 48,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 49,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 50,
    Name: "Shubham Joshi",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 51,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 52,
    Name: "Shubham Joshi",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 53,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 5,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 4,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 5,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 1,
    Name: "Shubham Joshi",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 2,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 3,
    Name: "Shubham Joshi",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 4,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 5,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 4,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 5,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Shubham Joshi",
    EmployeeImage: avatar2,
  },
];

export default employeesData;
